### ISSUE TITLE
My phone almost flip out of my hand trying to shake it work 

### ISSUE THREAD

**Issue by tranhuudang** [deven98/shake#16]
I have to shake my phone real hard to really see my phone responses to the move. Is it possible to modify the force we have to put on the shake ?

**Comment by d3xvn** [comment]
Hi,

You can look at the parameters of the class and modify the `shakeThresholdGravity` parameter. 
I am also working on a large update for this package at the moment to simplify all of these parameters.

Let me know if this helps.

**Comment by tranhuudang** [comment]
Oh, that was what I wanted. Thank you to much, you're doing a great job. I'm looking for your next exciting update.
