### ISSUE TITLE
Really inconsistent between Android & iOS

### ISSUE THREAD

**Issue by ciriousjoker** [deven98/shake#22]
I have two test devices:
- Pixel 4 XL
- iPhone SE 3rd gen

Same settings:
```dart
    minimumShakeCount: 3,
    shakeCountResetTime: 2000,
    shakeSlopTimeMS: 250,
    shakeThresholdGravity: 1.3,
```

On the Pixel, I need to shake really hard, on the iphone, regular movement is detected as shakes.
With the default value of 2.7 for the gravity thing, I had to literally throw my phone into a pillow for it to be detected...

Not quite sure if my phone is broken in this regard, if there's a huge difference between Android/iOS or if it's manufacturer-specific, which would be the worst.

The default value works really well for the iPhone though.

**Comment by ciriousjoker** [comment]
I've tested on another Android device (moto g5), it behaves roughly the same as on the iPhone. I guess my Pixel just has a broken sensor or something. We'll roll out the "shake to send feedback" feature to our users, let's see how many of them complain that it triggers accidentally or not easy enough.

**Comment by ciriousjoker** [comment]
Update: no user complained, I guess my phone is broken lol

**Comment by pauljonescodes** [comment]
I came here to look for issues related to it not working on Android/Pixel, and I was just not shaking hard enough apparently ...

THANK YOU
