### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by fabioselau077** [deven98/shake#3]
Hello, is this to check when the user shakes the phone?
How to do an installation? I'm used to installing it through pub.dev.
As it happens on Facebook when you shake your phone and a message appears to receive feedback, can you implement it with this package?

**Comment by d3xvn** [comment]
Hey @fabioselau077.

Yes, you can implement similar functionality with this package.

The general steps would be:

1) Add latest version of the package to your pubspec.yaml file.

2) In your code, add

```
ShakeDetector detector = ShakeDetector.autoStart(
    onPhoneShake: () {
        // Do stuff on phone shake
    }
);
```

and add your feedback form in the onPhoneShake method.

3) Cancel listening when done by calling:

`detector.stopListening();`
