### ISSUE TITLE
update to   sensors: ^2.0.0

### ISSUE THREAD

**Issue by sgehrman** [deven98/shake#5]
Because shake 0.1.0 depends on sensors ^0.4.0+1 and no versions of shake match >0.1.0 <0.2.0, shake ^0.1.0 requires sensors ^0.4.0+1.
So, because interview_dvx depends on both shake ^0.1.0 and sensors ^2.0.0, version solving failed.

**Comment by d3xvn** [comment]
This should be solved in the latest release. Feel free to reopen if required. Thanks for the issue!
